### ISSUE TITLE
Template for log file name

### ISSUE THREAD

**Issue by vadimkhm** [BedeGaming/sinks-rollingfile#29]
Hi, 
Is it possible to have file name template? or prefix template,
for example it will be great to have something like this: {Level}-{Date}-{Counter}, or only prefix
{Level}-...., {Some Text}-

Thanks and best,
Vadim

**Comment by pradeepneo** [comment]
@AndyWardle I have created pull request very similar to the request in this issue. We can pass a prefix to be appended to the current log file format https://github.com/BedeGaming/sinks-rollingfile/pull/33. Request you to review the same.

**Comment by vadimkhm** [comment]
Solved by #33
