### ISSUE TITLE
Logging from multiple threads?

### ISSUE THREAD

**Issue by syrotkin** [BedeGaming/sinks-rollingfile#35]
Hi!

I am wondering if the sink supports logging from multiple threads (within the same process). In the documentation I could only see that logging from multiple processes is not supported, so just wanted to check if logging from multiple threads was any different.

If we do need to log from multiple threads, do you think it might be enough to just introduce locking around each logging method call?

Thank you!

**Comment by ti24horas** [comment]
@syrotkin the multithreading is handled by serilog. This package is only a sink for Serilog, then it should work with multiple threads out of the box.
